---
title: "CpG Comparison between ElasticNet and Random Forest (SHAP)"
author: "Magalí Eisik"
output:
  html_document:
    df_print: paged
---


In this document, the top CpGs identified by SHAP importance were combined with their methylation status from the ElasticNet analysis. The resulting table is shown with colored formatting to indicate hyper- and hypomethylation. The table has also been saved as a CSV file for downstream analyses.


```{r message=FALSE,warning=FALSE}
# Load required packages
library(dplyr)
library(readr)
library(kableExtra)
library(ggplot2)
```



```{r}
#Read Csv files
shap_data <- read_csv("CpG_SHAP_importance.csv", col_types = cols(.default = "c"))
top20_cpgs <- read_csv("Top20_CpGs.csv", col_types = cols(.default = "c"))

```


```{r}
# Find CpGs in common
common_cpgs <- intersect(shap_data$CpG, top20_cpgs$CpG)
common_cpgs
```


```{r}
combined_data <- shap_data %>%
  dplyr::filter(CpG %in% common_cpgs) %>%
  dplyr::left_join(top20_cpgs[, c("CpG", "Methylation_Change")], by = "CpG") %>%
  dplyr::rename(Methylation_Status = Methylation_Change)
head(combined_data, 5)
```

```{r  message=FALSE,warning=FALSE}
combined_data <- combined_data %>%
  dplyr::mutate(Mean_SHAP = as.numeric(Mean_SHAP))
#Lollipop chart
ggplot(combined_data, aes(x = reorder(CpG, Mean_SHAP), y = Mean_SHAP, color = Methylation_Status)) +
  geom_segment(aes(x = CpG, xend = CpG, y = 0, yend = Mean_SHAP), size = 1) +
  geom_point(size = 3) +
  coord_flip() +
  scale_color_manual(values = c("Hypermethylated" = "#E74C3C", "Hypomethylated" = "#2E86C1")) +
  labs(title = "Top CpGs SHAP Importance",
       x = "CpG",
       y = "Mean SHAP value") +
  theme_minimal()
```


```{r}
#Save graph in png format
g1<- ggplot(combined_data, aes(x = reorder(CpG, Mean_SHAP), y = Mean_SHAP, color = Methylation_Status)) +
  geom_segment(aes(x = CpG, xend = CpG, y = 0, yend = Mean_SHAP), size = 1) +
  geom_point(size = 3) +
  coord_flip() +
  scale_color_manual(values = c("Hypermethylated" = "#E74C3C", "Hypomethylated" = "#2E86C1")) +
  labs(title = "Top CpGs SHAP Importance",
       x = "CpG",
       y = "Mean SHAP value") +
  theme_minimal()
ggsave("Top_CpGs_SHAP_Lollipop.png", plot = g1, width = 8, height = 6, dpi = 300)

```



```{r}
final_table <- combined_data %>%
  dplyr::select(CpG, Mean_SHAP, Methylation_Status) %>%
  dplyr::arrange(desc(Mean_SHAP))  

# Display table
final_table %>%
  knitr::kable(format = "html",
               caption = "<b>Top CpGs by SHAP Importance with Methylation Status</b>",
               align = "c") %>%
  kableExtra::kable_styling(full_width = FALSE,
                            bootstrap_options = c("striped", "hover", "condensed")) %>%
  kableExtra::column_spec(3, bold = TRUE,
                          color = "white",
                          background = ifelse(final_table$Methylation_Status == "Hypermethylated",
                                              "#E74C3C", "#2E86C1"))
```



```{r}
write.csv(final_table,
          "Top_CpGs_SHAP_with_Methylation.csv",
          row.names = FALSE)
```



