---
title: "Select the CPGs most correlated with age (GSE55763)"
author: "Magalí Eisik"
output:
  html_document:
    df_print: paged
---

```{r}
#Load require packages
library(dplyr)
library(readr)

```



```{r warning=FALSE}
# Load merged 1000 CpGs
top1000 <- read_csv("GSE55763_merged1000.csv", show_col_types = FALSE)

```




```{r}
#Verify dimensions and first 3 rows
dim(top1000)
head(top1000,3)
```


```{r}
# Extract CpG columns (columns 4 to 1003)
cpg_matrix <- top1000[, 4:ncol(top1000)]

# Extract age column
age <- top1000$age

# Compute correlations between each CpG and age
cor_values <- apply(cpg_matrix, 2, function(x) cor(x, age, method = "pearson"))

# Select top 500 CpGs most correlated with age
top500_cpg_names <- names(sort(abs(cor_values), decreasing = TRUE))[1:100]

# Subset the original dataframe to keep only top 500 CpGs
top500_df <- top1000[, c("X", "gender", "age", top500_cpg_names)]
```


```{r}
head(top500_df,3)
```

```{r}
# Create a dataframe of CpG and correlation
cor_df <- data.frame(
  CpG = names(cor_values),
  Correlation = cor_values
)

# Sort by absolute correlation decreasing
cor_df <- cor_df %>% arrange(desc(abs(Correlation)))
head(cor_df,3)
```


```{r}
library(ggplot2)


# Make a data frame for plotting
top100_cor_df <- data.frame(
  CpG = names(cor_values),
  Correlation = cor_values
)

# Histogram of correlation values
ggplot(top100_cor_df , aes(x = Correlation)) +
  geom_histogram(binwidth = 0.05, fill = "steelblue", color = "black") +
  theme_minimal() +
  labs(title = "Distribution of CpG Correlations with Age",
       x = "Pearson Correlation",
       y = "Number of CpGs")
```

```{r}
#save to CSV
write_csv(top500_df, "GSE55763_top500_beta_values.csv")
```

