---
title: "Exploratory Analysis GSE55763"
author: "Magalí Eisik"
output:
  html_document:
    df_print: paged
---

```{r, warning=FALSE}
#Load require packages
library(ggplot2)
library(FactoMineR)
library(factoextra)
library(kableExtra)
library(dplyr)
```




```{r}
#Load data set
GSE55763_100 <- read.csv("GSE55763_merged.csv", header = TRUE, stringsAsFactors = FALSE)

```


```{r}
#Verify dimensions and first rows
dim(GSE55763_100)
head(GSE55763_100,3)
```


Convert variables in the correct type:

```{r}
GSE55763_100$age <- as.numeric(GSE55763_100$age)
GSE55763_100$gender <- factor(GSE55763_100$gender, levels = c("M", "F"))
```


Visualizations

Age

```{r}
ggplot(GSE55763_100, aes(x = age)) +
  geom_histogram(binwidth = 5, fill = "violet", color = "black") +
  theme_minimal() +
  labs(title = "Age Distribution", x = "Age", y = "Samples")
```


Gender

```{r}
ggplot(GSE55763_100, aes(x = gender, fill = gender)) +
  geom_bar() +
  scale_fill_manual(values = c("steelblue", "pink")) +
  theme_minimal() +
  labs(title = "Gender Distribution", x = "Gender", y = "Samples")
```


Verify missing values


```{r}
n_samples <- nrow(GSE55763_100)
na_per_var <- colSums(is.na(GSE55763_100))
na_per_var <- na_per_var[na_per_var > 0]

na_df <- data.frame(
  Variable = names(na_per_var),
  Missing  = as.numeric(na_per_var),
  row.names = NULL   
) %>%
  filter(Missing > 0) %>%   
  arrange(desc(Missing))  

```


```{r}
na_df %>%
  kable("html", caption = "Variables with missing values") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"),
                full_width = FALSE)
```



```{r}
# Total number of values in the dataset
total_values <- nrow(GSE55763_100) * ncol(GSE55763_100)

# Total number of missing values
total_missing <- sum(is.na(GSE55763_100))

# Percentage of missing values
missing_pct <- (total_missing / total_values) * 100

# Print summary
cat(sprintf("The dataset contains %d missing values (%.4f%%).\n",
            total_missing, missing_pct))
```

In this case, missing values are assumed to be Missing Completely at Random (MCAR) and will be imputed using the median of each CpG.


```{r}
X_cpg <- GSE55763_100[, 4:103]  #select cpg columns
# Impute missing values using the median 
X_cpg_imputed <- as.data.frame(lapply(X_cpg, function(x) {
  x[is.na(x)] <- median(x, na.rm = TRUE)
  return(x)
}))
GSE55763_100_imputed <- cbind(GSE55763_100[, 1:3], X_cpg_imputed) #combine with other variables
sum(is.na(GSE55763_100_imputed)) #verify NAs
```

```{r}
# Save imputed daat set
write.csv(GSE55763_100_imputed, file = "GSE55763_100_imputed.csv", row.names = FALSE)
```



```{r,echo=FALSE}
# 1. Select CpG columns
X_cpg <- GSE55763_100_imputed[, 4:103]

# 2. Convert all columns to numeric
X_cpg <- as.data.frame(lapply(X_cpg, function(x) as.numeric(as.character(x))))

# 3. Calculate variance using sapply (safe for column names)
variances <- sapply(X_cpg, var)

# 4. Select top 30 most variable CpGs
top_cpgs <- names(sort(variances, decreasing = TRUE))[1:30]
X_cpg_top30 <- X_cpg[, top_cpgs]

# Check
head(X_cpg_top30)

```






PCA


```{r}
X_cpg_scaled <- scale(X_cpg_top30)
pca_res <- PCA(X_cpg_scaled, graph = FALSE)
```

```{r}
fviz_pca_ind(pca_res,
             geom.ind = "point",
             pointsize = 1.5,
             alpha.ind = 0.6,  # transparency
             col.ind = GSE55763_100_imputed$gender,
             palette = c("blue", "red"),
             addEllipses = TRUE)
```


```{r}
# Show only top 10 contributing CpGs
fviz_pca_var(pca_res, col.var = "contrib", 
             select.var = list(contribution = 10)) +
  theme_minimal()
```


```{r,echo=FALSE}
# Extract variable contributions
var_contrib <- pca_res$var$contrib

# Sum contributions over first 2 PCs
total_contrib <- rowSums(var_contrib[, 1:2])

# Create data frame with top 10 cpg
top10_df <- data.frame(
  CpG = names(total_contrib),
  Contribution = as.numeric(total_contrib)  # ensure numeric
) %>%
  arrange(desc(Contribution)) %>%
  slice(1:10)

# Print 
kable(top10_df, caption = "Top 10 CpGs contributing to PC1 and PC2")
```



The top 10 CpGs contributing most to PC1 and PC2 capture the main sources of variation in the dataset.

